# Generated by Django 4.2.13 on 2024-05-29 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userside', '0004_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikes', to='userside.posts')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
