# Generated by Django 4.2.13 on 2024-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
