# Generated by Django 4.2.13 on 2024-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_comments_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentime',
            new_name='comment_time',
        ),
    ]
