# Generated by Django 4.2.13 on 2024-07-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userside', '0009_userreports'),
        ('post', '0005_rename_commentime_comments_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField()),
                ('action_took', models.BooleanField(default=False)),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_posts', to=settings.AUTH_USER_MODEL)),
                ('reported_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_post_reports', to='userside.posts')),
            ],
        ),
    ]
