# Generated by Django 4.2.13 on 2024-06-26 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('time_triggered', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_send', models.BooleanField(default=False)),
                ('invoked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoked_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
