# Generated by Django 4.2.13 on 2024-07-24 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_read_users',
            field=models.ManyToManyField(blank=True, related_name='chatsReadByUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['room'], name='chat_chat_room_id_493a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['sender'], name='chat_chat_sender__1929eb_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['message_time'], name='chat_chat_message_e2ce64_idx'),
        ),
    ]
