# Generated by Django 4.2.13 on 2024-07-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_is_read_chat_chat_read_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_read_users',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
