# Generated by Django 4.2.13 on 2024-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_regotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='regotp',
            name='otp_time',
            field=models.DateTimeField(null=True),
        ),
    ]
