# Generated by Django 4.2.13 on 2024-05-24 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_regotp_otp_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('contend', models.ImageField(upload_to='postImages/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
