# Generated by Django 4.2.13 on 2024-06-29 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField()),
                ('action_took', models.BooleanField(default=False)),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_users', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allreports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
