# Generated by Django 4.2.13 on 2024-07-13 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_userreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='verificationDocs/')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('plan_choosed', models.CharField(choices=[('6_month', '6 Months'), ('12_month', '12 Months'), ('1_year', '1 Year')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscribed_date', models.DateTimeField(blank=True, null=True)),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varifiedUsers', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
