# Generated by Django 4.2.13 on 2024-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0011_alter_verification_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='plan_choosed',
            field=models.CharField(blank=True, choices=[('6_month', '6 Months'), ('12_month', '12 Months'), ('1_year', '1 Year')], max_length=20, null=True),
        ),
    ]
