# Generated by Django 4.2.13 on 2024-07-16 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_alter_verification_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificationData', to=settings.AUTH_USER_MODEL),
        ),
    ]
