# Generated by Django 4.2.13 on 2024-07-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0013_alter_verification_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='plan_choosed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
