# Generated by Django 4.2.13 on 2024-07-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0015_customuser_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='document',
        ),
        migrations.AddField(
            model_name='verification',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
